### ISSUE TITLE
Improper handling of `max_bot_version` when below `min_bot_version`

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Cog-Browser#12]
Per the [Info.json docs](https://docs.discord.red/en/latest/guide_publish_cogs.html#info-json-format), if `min_bot_version` is newer than `max_bot_version`, `max_bot_version` will be ignored. Currently the index does not follow this behavior, instead setting the `max_bot_version` equal to the `min_bot_version`.

This can be seen with any cog from `cbd-cogs`.

Cog info.json:
![image](https://user-images.githubusercontent.com/34169552/97758103-90395f00-1ad4-11eb-991b-67789d0ff48d.png)

Index:
![image](https://user-images.githubusercontent.com/34169552/97758120-992a3080-1ad4-11eb-8418-3a1d39d762ce.png)

**Comment by Eslyium** [comment]
Iv been thinking about this, Should we just limit this to a single call? Min or Max?

**Comment by Eslyium** [comment]
Iv fixed the main cause of it due to putting min twice in the index.php because lets face it im not too sharp :)
But my question still remains

**Comment by Jackenmen** [comment]
`max_bot_version` should not be shown at all if it's lower than `min_bot_version` as it does not apply in such cases and it's documented to be ignored.

As for the cases where both `min_bot_version` and `max_bot_version` apply (so in cases where `max_bot_version` is not lower than `min_bot_version`), I guess it would look nicer if they were combined in one line, but it would need to be done in a readable way so that people know that any version between those two can be used. I don't know what that would be though.

We could also additionally special case `min_bot_version` and `max_bot_version` being equal and only show `==1.2.3` in that case, rather than sth like `>=1.2.3,<=1.2.3`.

**Comment by Eslyium** [comment]
Done.
