### ISSUE TITLE
Sort by metadata

### ISSUE THREAD

**Issue by chaos-baum** [Cog-Creators/Cog-Browser#25]
I think it would be very nice if you could sort and/or filter by metadata of a cog.
I think #22 is a good start for that. But additional to updated and created something like repo stars would be super helpfull. 
Even better would be a stat that shows how many bot have installed a specific cog but i think that is not feasable to implement

**Comment by aikaterna** [comment]
We won't be adding any sort of ranking system or a way to indicate usage volume, as we believe that shouldn't be our place to favor someone's cog over another for whatever reason(s). This has been suggested in the past but we've always declined this sort of request because of this fact. Everyone's Red instance is different, and folks can try out cogs that they think will work best for them and use what they find appropriate without any kind of prioritized list or favoritism coming from the folks that are maintaining the project and overall cog ecosystem.

**Comment by chaos-baum** [comment]
I get your point, and it's totally valid. But I still think adding a bit more metadata, like showing when a cog was created and last updated, wouldn’t hurt. It would actually be helpful for users to see how active or up-to-date a cog is, like what’s being suggested in [this PR](https://github.com/Cog-Creators/Red-Index/pull/93).

What do you think? Could be a nice balance between transparency and keeping things simple.

**Comment by Jackenmen** [comment]
> But I still think adding a bit more metadata, like showing when a cog was created and last updated, wouldn’t hurt.

Hence why both #16 and the linked PR are still open.

**Comment by yamikaitou** [comment]
Metadata cannot tell you if a cog is up-to-date other than what is already displayed (the Bot Version field). A cog can be fully functional but not updated since 3.5 came out.
