### ISSUE TITLE
Could search be made more forgiving?

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Cog-Browser#5]
Right now, search requires the cog name/description to match exactly to be found, there's no room for typos.
For example, writing `roels` rather than `roles` or `ccroles` rather than `ccrole` will return no matches.

**Comment by Eslyium** [comment]
Ill take a look into this and get back to you on it, I'm unsure how much it'll effect the searching with typos and searching the json file so id like to build it and test it out first before fully approving this.

**Comment by Eslyium** [comment]
Hello there,

After looking into this pretty deeply and breaking things over and over again I have determined that this is not currently possible at this moment due to the structure of the json and the way we currently use tags, Right now it mainly searches if the term/name is within the description/name. 

If we are able to streamline the tag system down more to a generic/structure approach this may be easier in the future.
