### ISSUE TITLE
Maybe the warning about unapproved cogs should require agreement?

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Cog-Browser#6]
Currently, you can check the unapproved checkbox and you will only see the warning *after* you already check it, which allows you to just skip through it. Maybe the warning about unapproved cogs should require an actual agreement, like, for example, in dev.v3.cogs.red?
GIF of how it looks like on dev.v3.cogs.red:
![2020-09-15_12-11-10](https://user-images.githubusercontent.com/6032823/93198190-f3517b00-f74c-11ea-91a0-1cc81062fe90.gif)

**Comment by Eslyium** [comment]
I'm open for discussion about this, I personally don't want a popup box on this but I don't want my personal feelings dismissing what the org wants.

While the user can "skip" over it, It still reloads the page to the top after you click the button and then you have to search again, Seeing a red box under the search, Its not hard to miss honestly.

The purpose of this was/is to be lightweight and non-annoyance to the end user with minimal issues and not something overly complicated.

**Comment by aikaterna** [comment]
With the discussion regarding unapproved vs approved in the early days of v3 QA and defining what those mean to our users this time around, we went with more of a strict path for unapproved repos this time around vs v2. Imo anything we can do to make unapproved listings obnoxious to users (popup, agreement, etc) is something we should pursue this time around. 

Personally, outside of the "official" feelings regarding unapproved vs approved, I feel the plain text box is fine. But our conditions this time around direct me to believe that we need something like the popup box (and/or anything else we asked Orels to do for v3.cogs.red over the years for unapproved listings).

**Comment by Jackenmen** [comment]
I guess we could also do something in the middle - i.e. we could not require to type "I agree", and just have a confirmation prompt with a checkbox and a button (or *maybe* just a button, although I'm personally against having *just a button*). I don't think it would be as effective though.
// I haven't tested, but is the checkbox state saved with cookies? If it is, I think this isn't really all that annoying even with what I proposed originally in the issue description.

**Comment by Flame442** [comment]
I don't think it needs to be a popup specifically, but something that says "I read the message" at least. Whether that be a second checkbox like jack said or a "type exactly this here" like in orel's version, I don't really think it matters.

**Comment by Drapersniper** [comment]
Overall I'm in favour of the idea behind the new cog browser, but do think it needs to be obnoxious more so users that don't read stuff are forced to a knowledge it here driving people to go back and read properly not everyone but a large part

**Comment by Twentysix26** [comment]
My opinion, which I see goes against most here:
there's a very thin line between giving the user a reasonable warning about what to expect and building a needlessly obnoxious UI for it.  
The current warning, a big red box with white capital letters, is basically impossible to miss.
Would a popup be even more in your face about it, forcing you to type (!) and interact with it to close it? Yes
Would it make a difference for a user willing to ignore the current big ass warning? Hardly
There are a way bigger user content repositories out there (that host the files themselves instead of just being an index like this one) that could, and in the past already happened to, contain malicious code. Maybe you'll just see a [warning in bold characters in their homepage](https://aur.archlinux.org/), maybe [not even that](https://pypi.org/).  
Why should ours be any different, considering that we're not even hosting anything to begin with?

**Comment by Eslyium** [comment]
This is complete,
![image](https://user-images.githubusercontent.com/18387809/93404221-9e4e5b80-f857-11ea-9be9-f2fe23631d7f.png)

Thanks for the input.
