### ISSUE TITLE
Links can't open in new tab

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Cog-Browser#7]
The tag links, "view repository" link, and the author links can't be opened in new tab with any of:
- Ctrl + Left mouse button click
- Middle mouse button click
- Right click and Open in new tab ("Open in new tab" simply isn't in the context menu as it isn't treated as link)

**Comment by Eslyium** [comment]
Heres my thoughts

Top buttons have onclick function that just opens it in a new tab.
View repository links can be changed to what you have currently PR'd

**Comment by Twentysix26** [comment]
> Top buttons have onclick function that just opens it in a new tab.

Having the top buttons be proper links also allows for the destination URL to show in the status bar. As a user I prefer a web page's links to be actual `a` links, because usually any alternative solution breaks many standard behaviors as it's happening here (right click not working, middle click not working, etc). I assume Jack's fix covers that. If his solution doesn't change the current style I'm in favor of it
